version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: indexer-db
      
  indexer:
    image: subsquid/hydra-indexer:3
    restart: unless-stopped
    environment:
      - INDEXER_WORKERS=5
      - DB_NAME=indexer-db
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index*
      - TYPES_JSON=acala-types.json 
      - SPEC_TYPES=acala-typesBundle.json
      - BLOCK_HEIGHT=44070
      - WS_PROVIDER_ENDPOINT_URI=wss://karura-rpc-3.aca-api.network/ws
    volumes:
       - "./acala-types.json:/home/hydra/packages/hydra-indexer/acala-types.json"
       - "./acala-typesBundle.json:/home/hydra/packages/hydra-indexer/acala-typesBundle.json"
    depends_on: 
      - db
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
  
  indexer-api-gateway:
    image: subsquid/hydra-indexer-gateway:3
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=${DB_PASS}
      - WARTHOG_STARTER_DB_PORT=${DB_PORT}
      - WARTHOG_STARTER_DB_USERNAME=${DB_USER}
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
    ports:
      - "4001:4000" # 
    depends_on:
      - redis
      - indexer
    
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379"
